# Generated by Django 5.2 on 2026-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0086_repository_org_root_link_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='source_provider',
            field=models.CharField(blank=True, choices=[('GOOGLE_DRIVE', 'Google Drive'), ('ONE_DRIVE', 'OneDrive'), ('LOCAL', 'Local')], help_text='Source provider of the media (e.g. Google Drive, OneDrive, Local)', max_length=100, null=True),
        ),
    ]
