# Generated by Django 5.2 on 2026-07-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0086_repository_org_root_link_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='source_provider',
            field=models.CharField(blank=True, choices=[('GOOGLE_DRIVE', 'Google Drive'), ('ONE_DRIVE', 'OneDrive'), ('AWS_S3', 'AWS S3'), ('LOCAL_UPLOAD', 'Local Upload')], help_text='Source provider of the media (e.g. Google Drive, OneDrive, AWS S3)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='source_provider',
            field=models.CharField(blank=True, choices=[('GOOGLE_DRIVE', 'Google Drive'), ('ONE_DRIVE', 'OneDrive'), ('AWS_S3', 'AWS S3'), ('LOCAL_UPLOAD', 'Local Upload')], help_text='Source provider of the media (e.g. Google Drive, OneDrive, AWS S3)', max_length=100, null=True),
        ),
    ]
