TOKEN_PATTERN = r"[A-Za-z0-9']+"
ALNUM_TOKEN_PATTERN = r"[A-Za-z0-9]+"
LOWER_ALNUM_TOKEN_PATTERN = r"[a-z0-9]+"
LOWER_TOKEN_PATTERN = r"[a-z0-9']+"
DOES_NOT_EXIST_PATTERN = r"\bdoes\s+not\s+exist\b"
PUNCTUATION_SEPARATOR_PATTERN = r"[,;]+"
WHITESPACE_PATTERN = r"\s+"
EXTENSION_PATTERN = r"\.[a-z0-9]+"
EXTENSION_BOUNDARY_PATTERN_TEMPLATE = r"(?<![a-z0-9]){}\b"
WORD_BOUNDARY_PATTERN_TEMPLATE = r"\b{}\b"
EXACT_SPAN_PATTERN_TEMPLATE = r"(?<!\w){}(?!\w)"
FLEXIBLE_NAME_SEPARATOR_PATTERN = r"[\s\-_./]*"
ALNUM_BOUNDARY_PATTERN = r"(?<=[A-Za-z])(?=\d)|(?<=\d)(?=[A-Za-z])"
DOC_WORD_PATTERN = r"\bdoc\b"
DOC_EXPLICIT_CONTEXT_PATTERN = r"\s+(?:file|files|format|formats)\b"
COORDINATION_BEFORE_PATTERN = r"(?:,|\b(?:or|and)\b)\s*$"
COORDINATION_AFTER_PATTERN = r"\s*(?:,|\b(?:or|and)\b)"
TOPIC_PROTECTED_SPAN_PATTERN = (
    r"\b(?:about|regarding|related to|covering|on)\b\s+([^,;]+)"
)
ONLY_PATTERN = r"\bonly\b"
NEITHER_PATTERN = r"\bneither\b"
